import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ConditionalNav from "./components/ConditionalNav";
import ConditionalWrapper from "./components/ConditionalWrapper";
import UserButton from "./components/UserButton";
import MobileNav from "./components/MobileNav";
import TopLoader from "./components/TopLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopLoader />
        <ConditionalNav>
          <header className="nav-wrap">
            <nav className="site-nav" aria-label="Main navigation">
              <div className="brand cursor-pointer">
                <Link href="/">Manhua Rush</Link>
              </div>

              <ul className="breadcrumb" role="list">
                <li><Link className="nav-link" href="/">Home</Link></li>
                <span>/</span>
                <li><Link className="nav-link" href="/collections/all?p=all">Collections</Link></li>
                <span>/</span>
                <li><Link className="nav-link" href="/craft?mode=dev">Craft</Link></li>
              </ul>

              <div className="nav-right">
                <UserButton />
              </div>

              {/* Mobile hamburger (hidden on desktop) */}
              <MobileNav />
            </nav>
          </header>
        </ConditionalNav>

        <ConditionalWrapper>{children}</ConditionalWrapper>
      </body>
    </html>
  );
}
